### ISSUE TITLE
Semantic Data Alias

### ISSUE THREAD

**Issue by FauconFan** [Heijix/nut-lang#20]
What is the best:

```
Alias Time :- float
```

```
Alias Time := float
```

Difference between ':-' ':='

**Comment by FauconFan** [comment]
Same as Data Picture :=

**Comment by xavitator** [comment]
I agree that is better to have ":=" !

**Comment by FauconFan** [comment]
@elusyo

**Comment by elusyo** [comment]
It's like language definition so more common.
Agree to ":="
