### ISSUE TITLE
Change how to handle numbers

### ISSUE THREAD

**Issue by FauconFan** [Heijix/nut-lang#21]
Numbers are hard typed.
It meens that 

2 is not a flottant

2. is not a int.

We have to change the grammar to accept the following as flottants.

```
2.
.23
```

Is it okay for you ?

**Comment by xavitator** [comment]
it is okey for me ;)

**Comment by FauconFan** [comment]
@elusyo

**Comment by elusyo** [comment]
Ok for me.

**Comment by FauconFan** [comment]
32c54e25dec070c393aed2e7a88951561b48bdb8
