### ISSUE TITLE
Change of integer type

### ISSUE THREAD

**Issue by xavitator** [Heijix/nut-lang#25]
It is a proposition of @FauconFan : 

There is some language where char, short, int and long primitive variables are not defined to have respectively 8, 16, 32 and 64 bits (such as in C for int).
So we can introduce : 
- int8
- int16
- int32
- int64

to replace this language restriction.

And add 'u' before them to have an unsigned value.

**Comment by FauconFan** [comment]
Refer #19 

Otherwise, it's a godd idea for me
